### ISSUE TITLE
Not running on GPU

### ISSUE THREAD

**Issue by mudasser-rafi** [deshwalmahesh/yolov7-deepsort-tracking#3]
Hi, 

I tried to run this on my local machine. But it's using CPU only. Not running on GPU.
Is there a way to force it to run in CPU+GPU?

**Comment by Kannan665** [comment]
I had used docker to set the dev environment and I had run all the codes successfully, since Torch and Tensorflow in the environment were compiled from source and cuda/cudnn were installed along with it.....Can you post screenshots of your system when you mentioned it is running only on CPU? I use "nvitop -m auto" to check the resource utilization, while running training or inferencing? 
You can install it from............https://pypi.org/project/nvitop/
Regards..........Kannan Rama
