### ISSUE TITLE
Save a txt or xls file of the resulted tracking

### ISSUE THREAD

**Issue by Sarouch** [deshwalmahesh/yolov7-deepsort-tracking#7]
Hello,
Thank you for this repo ! 
As the code is wraped, could you tell me where can I save the .txt file (or xls file) of all the information I obtained from the tracking (selecting verbose 2) as you can see in this picture please ?
![image](https://user-images.githubusercontent.com/40342672/191050511-be02d064-4e96-436c-87c3-fac6d2682c78.png)

**Comment by deshwalmahesh** [comment]
Sure. So this information is being generated from [bridge_wrapper.py](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/bridge_wrapper.py). What you can do is to find all the `print` statements starting from `Line 87: While True:`, and instead of printing it, you could simply save whatever information is there.

For example, this `Tracker ID: 11674, Class: .....` is coming from `Line 157-158`.

**Comment by Sarouch** [comment]
> Sure. So this information is being generated from [bridge_wrapper.py](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/bridge_wrapper.py). What you can do is to find all the `print` statements starting from `Line 87: While True:`, and instead of printing it, you could simply save whatever information is there.
> 
> For example, this `Tracker ID: 11674, Class: .....` is coming from `Line 157-158`.

Yes this is what I did thank you.
