### ISSUE TITLE
Train deepSort on custom data

### ISSUE THREAD

**Issue by Sarouch** [deshwalmahesh/yolov7-deepsort-tracking#8]
Hello,
I have really a bad results on my customs data set, even the bbox are outide the object ! Knowing that the mAP of these same data was great while using yolov7 !  
Should I train deepSort on my custom dataset ? Please, do you have an idea how can I do that ? I know that deepSort first, was trained on persons data... Thanks in advance.

**Comment by deshwalmahesh** [comment]
if `mAP` for detection is good, only problem might be either the detection model is  is over fitting or you have problem with `DeepSORT`. Some examples are:

1. Maybe you are skipping frames while inference
2.  Objects are not people as this specific model is for people only
3. Code is using wrong classes in the config so MAYBE

**Comment by Sarouch** [comment]
> if `mAP` for detection is good, only problem might be either the detection model is is over fitting or you have problem with `DeepSORT`. Some examples are:
> 
> 1. Maybe you are skipping frames while inference
> 2. Objects are not people as this specific model is for people only
> 3. Code is using wrong classes in the config so MAYBE

Yes I think mars-small128.pb doesn't work good at my own datasets, because of that, I trained deepSort with my custom data and obtained a weights but on pytorch format (.pt), I will try to figure out how to convert it to tensorflow format (.pb) and try again ! Thanks

**Comment by YLL0209** [comment]
> > if `mAP` for detection is good, only problem might be either the detection model is is over fitting or you have problem with `DeepSORT`. Some examples are:
> > 
> > 1. Maybe you are skipping frames while inference
> > 2. Objects are not people as this specific model is for people only
> > 3. Code is using wrong classes in the config so MAYBE
> 
> Yes I think mars-small128.pb doesn't work good at my own datasets, because of that, I trained deepSort with my custom data and obtained a weights but on pytorch format (.pt), I will try to figure out how to convert it to tensorflow format (.pb) and try again ! Thanks

Helo, can you show me reference on how to trained deepsort model with own custom data? Thank you very much.

**Comment by deshwalmahesh** [comment]
@YLL0209  You can follow the whole threads and references for these below

1. [Training yout own feature Exractor](https://nanonets.com/blog/object-tracking-deepsort/#deep-sort:~:text=a%20torch%20tensor.-,Training%20your%20own%20feature%20extractor,-Since%2C%20the%20original)
2. [Code for training feature extractor](https://nanonets.com/blog/object-tracking-deepsort/#deep-sort:~:text=a%20torch%20tensor.-,Training%20your%20own%20feature%20extractor,-Since%2C%20the%20original)
3. [Siamese Network](https://pyimagesearch.com/2020/11/30/siamese-networks-with-keras-tensorflow-and-deep-learning/)
4. [Training a custom dataset for deep sort](https://github.com/nwojke/cosine_metric_learning/issues/5)
5. [How can I train deep sort using my own images](https://github.com/ZQPei/deep_sort_pytorch/issues/7)
6.

**Comment by 108618026** [comment]
> if `mAP` for detection is good, only problem might be either the detection model is is over fitting or you have problem with `DeepSORT`. Some examples are:
> 
> 1. Maybe you are skipping frames while inference
> 2. Objects are not people as this specific model is for people only
> 3. Code is using wrong classes in the config so MAYBE

Hello @deshwalmahesh 
If my task is only for person, all I need to do is finetune the YOLOv7 model?
Am I right?

Thanks in advanced!

**Comment by deshwalmahesh** [comment]
@108618026  You can fine tune both the `Yolov7` and `ReID` model for person in case you want a production level implementation. Default model weights for `ReiD` are old and new data + models + losses+ research has been done so there are new benchmarks for persona similarity and you can use those wights or techniques.
